import { defineConfig } from 'vitest/config';

// Windows security tests invoke the platform ACL verifier repeatedly across
// multi-step database workflows, and macOS hosted runners are similarly slow
// for suites that spawn real child processes (agent broker, packed runs).
// Keep the fail-closed checks real while giving the process boundary enough
// time on every hosted runner; fast suites still finish in milliseconds.
const testBoundaryTimeoutMs = process.platform === 'win32' ? 360_000 : 120_000;

// Every suite must be hermetic: commands fall back to the real per-user
// datastore profile registry under the home directory, so each worker gets an
// isolated fake home and can never observe or mutate machine-local Kavrix state.
export default defineConfig({
  test: {
    setupFiles: ['./scripts/test-isolated-home.mjs'],
    fileParallelism: process.platform !== 'win32',
    hookTimeout: testBoundaryTimeoutMs,
    include: [
      'apps/cli/test/database-session.test.ts',
      'apps/cli/test/database-doctor-repair.test.ts',
      'apps/cli/test/acl-probe.test.ts',
      'apps/cli/test/database-commands.test.ts',
      'apps/cli/test/database-flat-commands.test.ts',
      'apps/cli/test/database-migration.test.ts',
      'apps/cli/test/datastore-profile-publication.test.ts',
      'apps/cli/test/datastore-profiles.test.ts',
      'apps/cli/test/init-onboarding.test.ts',
      'apps/cli/test/init-onboarding-command.test.ts',
      'apps/cli/test/init-storage-selection.test.ts',
      'apps/cli/test/local-vault-cli-publication.test.ts',
      'apps/cli/test/local-vault-cli-coverage.test.ts',
      'apps/cli/test/local-vault-cli-view.test.ts',
      'apps/cli/test/execution-agent.test.ts',
      'apps/cli/test/execution-confirm.test.ts',
      'apps/cli/test/execution-exit-codes.test.ts',
      'apps/cli/test/execution-internals.test.ts',
      'apps/cli/test/broker-protocol.test.ts',
      'apps/cli/test/execution-project-config.test.ts',
      'apps/cli/test/execution-run-options.test.ts',
      'apps/cli/test/execution-units.test.ts',
      'apps/cli/test/execution-guards.test.ts',
      'apps/cli/test/execution-input-guards.test.ts',
      'apps/cli/test/execution-render.test.ts',
      'apps/cli/test/execution-signals.test.ts',
      'apps/cli/test/execution-policy.test.ts',
      'apps/cli/test/execution-policy-grants.test.ts',
      'apps/cli/test/execution-run.test.ts',
      'apps/cli/test/execution-run-grants.test.ts',
      'apps/cli/test/report-regressions.test.ts',
      'apps/cli/test/execution-executable.test.ts',
      'apps/cli/test/execution-engine.test.ts',
      'apps/cli/test/local-secrets.test.ts',
      'apps/cli/test/package.test.ts',
      'packages/schemas/test/database-container.test.ts',
      'packages/schemas/test/**/*.test.ts',
      'packages/crypto/test/**/*.test.ts',
      'packages/runner/test/**/*.test.ts',
      'packages/key-files/test/secure-stream.test.ts',
      'packages/key-files/test/sealed-secret-store.test.ts',
      'packages/key-files/test/portable-key-files.test.ts',
      'packages/key-files/test/revision-anchor.test.ts',
      'packages/key-files/test/canonical-json-document.test.ts',
      'packages/key-files/test/canonical-json-document-failure.test.ts',
      'packages/key-files/test/recovery-kit-files.test.ts',
      'packages/key-files/test/database-key-files.test.ts',
      'packages/key-files/test/database-recovery-kit-files.test.ts',
      'packages/key-files/test/database-revision-anchor.test.ts',
      'packages/key-files/test/authorization-state-file.test.ts',
      'packages/key-files/test/database-owned-publication.test.ts',
      'packages/key-files/test/filesystem-coverage.test.ts',
      'packages/key-files/test/filesystem-windows-acl.test.ts',
      'packages/key-files/test/windows-acl.test.ts',
      'packages/storage/test/file-local-vault.test.ts',
      'packages/storage/test/file-encrypted-database.test.ts',
      'packages/storage/test/stale-lock-recovery.test.ts',
      'packages/storage/test/encrypted-database-store-contract.test.ts',
      'packages/storage/test/mongo-encrypted-database.test.ts',
      'packages/storage/test/mongo-encrypted-database.integration.test.ts',
      'packages/storage/test/mongo-local-vault.test.ts',
      'packages/storage/test/mongo-local-vault-uri.test.ts',
      'packages/tui/test/**/*.test.ts',
    ],
    passWithNoTests: false,
    restoreMocks: true,
    unstubEnvs: true,
    unstubGlobals: true,
    testTimeout: testBoundaryTimeoutMs,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary', 'html'],
      include: [
        'apps/cli/src/**/*.{ts,tsx}',
        'packages/schemas/src/**/*.{ts,tsx}',
        'packages/crypto/src/**/*.{ts,tsx}',
        'packages/runner/src/**/*.{ts,tsx}',
        'packages/key-files/src/**/*.{ts,tsx}',
        'packages/storage/src/**/*.{ts,tsx}',
        'packages/tui/src/**/*.{ts,tsx}',
      ],
      exclude: ['**/src/index.ts'],
      thresholds: {
        branches: 80,
        functions: 85,
        lines: 85,
        statements: 85,
      },
    },
  },
});
