export * from './errors.js';
export {
  AuthorizationStateFileError,
  AUTHORIZATION_STATE_SUFFIX,
  authorizationStatePath,
  initializeAuthorizationStateFile,
  readAuthorizationStateFile,
  transitionAuthorizationStateFile,
  type AuthorizationScope,
  type AuthorizationStateErrorCode,
  type AuthorizationStateTransition,
} from './authorization-state-file.js';
export {
  SealedSecretStore,
  sealedEntryFactory,
  type SealedSecretStoreOptions,
} from './sealed-secret-store.js';
export { setWindowsUserOnlyAcl, verifyWindowsUserOnlyAcl } from './windows-acl.js';
export {
  MAX_SECURE_STREAM_CHUNK_BYTES,
  MAX_SECURE_STREAM_FILE_BYTES,
  deleteSecureFile,
  ensureSecureDirectory,
  readSecureFile,
  releaseOwnedSecureFilePublication,
  validateSecureFileDestination,
  validateSecureFileSource,
  writeSecureStreamFile,
  type SecureFileStreamWriteResult,
} from './filesystem.js';
export {
  readProtectedJsonDocument,
  transitionProtectedJsonDocument,
  transitionProtectedJsonDocumentWithPublicationStatus,
  writeProtectedJsonDocument,
  ProtectedJsonDocumentError,
  type CanonicalJsonDocumentSchema,
  type ProtectedJsonDocumentOptions,
  type ProtectedJsonDocumentPublication,
  type ProtectedJsonDocumentTransition,
  type ProtectedJsonDocumentTransitionPublicationResult,
} from './canonical-json-document.js';
export {
  readPortableKeyFile,
  validatePortableKeyFile,
  writePortableKeyFile,
  type ParsedPortableKeyFile,
  type PortableKey,
  type PortableKeyFileBinding,
  type PortableKeyFileProtection,
  type PortableKeyFileWriteOptions,
} from './portable-key-files.js';
export {
  readRecoveryKitFile,
  writeRecoveryKitFile,
  type ParsedRecoveryKit,
  type RecoveryKitBinding,
} from './recovery-kit-files.js';
export {
  copyRevisionAnchor,
  readRevisionAnchor,
  validateRevisionAnchorFile,
  writeRevisionAnchor,
  type RevisionAnchor,
} from './revision-anchor.js';
export {
  cleanupOwnedDatabaseKeyFile,
  consumeDatabaseLocalShareBootstrap,
  createOwnedDatabaseKeyFile,
  createOwnedDatabaseLocalShareKeyFile,
  releaseOwnedDatabaseKeyFile,
  readDatabaseKeyFileBinding,
  readDatabaseKeyFile,
  writeDatabaseKeyFile,
  type DatabaseKeyBinding,
  type DatabaseKeyFileCreateOptions,
  type DatabaseKeyFileCreateResult,
  type DatabaseKeyFilePublication,
  type DatabaseKeyFileWriteOptions,
  type ParsedDatabaseKeyFile,
} from './database-key-files.js';
export {
  cleanupOwnedDatabaseRecoveryKitFile,
  createOwnedDatabaseRecoveryKitFile,
  releaseOwnedDatabaseRecoveryKitFile,
  readDatabaseRecoveryKitFileBinding,
  readDatabaseRecoveryKitFile,
  writeDatabaseRecoveryKitFile,
  type DatabaseRecoveryBinding,
  type DatabaseRecoveryKitCreateOptions,
  type DatabaseRecoveryKitFileCreateResult,
  type DatabaseRecoveryKitFilePublication,
  type DatabaseRecoveryKitWriteOptions,
  type ParsedDatabaseRecoveryKit,
} from './database-recovery-kit-files.js';
export {
  cleanupOwnedDatabaseRevisionAnchor,
  createOwnedDatabaseRevisionAnchor,
  databaseRevisionAnchorPath,
  databaseRevisionAnchorSchema,
  databaseVaultRevisionAnchorSchema,
  readDatabaseRevisionAnchor,
  releaseOwnedDatabaseRevisionAnchor,
  transitionDatabaseRevisionAnchor,
  transitionOwnedDatabaseRevisionAnchor,
  verifyDatabaseRevisionAnchor,
  writeDatabaseRevisionAnchor,
  type DatabaseRevisionAnchor,
  type DatabaseRevisionAnchorCreateResult,
  type DatabaseRevisionAnchorPublication,
  type DatabaseRevisionAnchorVerificationOptions,
  type DatabaseRevisionAnchorTransitionResult,
  type DatabaseVaultRevisionAnchor,
  type OwnedDatabaseRevisionAnchorTransitionResult,
} from './database-revision-anchor.js';
export * from './collaboration-identity.js';
export * from './collaboration-migration-journal.js';
export {
  COLLABORATION_AUTHORITY_ROLLBACK_ANCHOR_FORMAT,
  COLLABORATION_AUTHORITY_ROLLBACK_ANCHOR_SUFFIX,
  COLLABORATION_AUTHORITY_ROLLBACK_ANCHOR_VERSION,
  collaborationAuthorityRollbackAnchorFromCollaborativeVaultDocument,
  collaborationAuthorityRollbackAnchorPath,
  collaborationAuthorityRollbackAnchorSchema,
  createCollaborationAuthorityRollbackAnchor,
  readCollaborationAuthorityRollbackAnchor,
  transitionCollaborationAuthorityRollbackAnchor,
  verifyCollaborationAuthorityRollbackAnchor,
  type CollaborationAuthorityRollbackAnchor,
  type CollaborationAuthorityRollbackAnchorChainVerification,
  type CollaborationAuthorityRollbackAnchorScope,
  type CollaborationAuthorityRollbackAnchorTransitionResult,
  type CollaborationAuthorityRollbackAnchorVerificationOptions,
} from './collaboration-authority-anchor.js';
export {
  createRecipientRollbackAnchor,
  readRecipientRollbackAnchor,
  RECIPIENT_ROLLBACK_ANCHOR_SUFFIX,
  computeFinalizedMutationLinkDigest,
  recipientRollbackAnchorFromCollaborativeVaultDocument,
  recipientRollbackAnchorPath,
  transitionRecipientRollbackAnchor,
  verifyRecipientRollbackAnchor,
  type RecipientRollbackAnchor,
  type RecipientRollbackAnchorScope,
  type RecipientRollbackAnchorTransitionResult,
  type RecipientRollbackAnchorChainVerification,
  type RecipientRollbackAnchorVerificationOptions,
} from './collaboration-anchor.js';
export {
  COLLABORATIVE_OPERATION_JOURNAL_FORMAT,
  COLLABORATIVE_OPERATION_JOURNAL_SUFFIX,
  COLLABORATIVE_OPERATION_JOURNAL_VERSION,
  collaborativeOperationJournalActiveSchema,
  collaborativeOperationJournalPath,
  collaborativeOperationJournalRecordSchema,
  collaborativeOperationJournalTerminalSchema,
  createCollaborativeOperationJournal,
  readCollaborativeOperationJournal,
  reconcileCollaborativeOperationJournal,
  type CollaborationOperationJournalAccessMode,
  type CollaborationOperationJournalCreateInput,
  type CollaborationOperationJournalReadOptions,
  type CollaborationOperationJournalScope,
  type CollaborationRecoveryRestartEvidence,
  type CollaborativeOperationJournalActiveRecord,
  type CollaborativeOperationJournalRecord,
  type CollaborativeOperationJournalTerminalRecord,
} from './collaboration-operation-journal.js';
export {
  RECIPIENT_VAULT_DESTRUCTION_ANCHOR_SUFFIX,
  createOrVerifyRecipientVaultDestructionAnchor,
  createRecipientVaultDestructionAnchor,
  readRecipientVaultDestructionAnchor,
  recipientVaultDestructionAnchorFromTombstone,
  recipientVaultDestructionAnchorPath,
  type RecipientVaultDestructionAnchor,
  type RecipientVaultDestructionAnchorScope,
} from './collaboration-destruction-anchor.js';
export {
  COLLABORATIVE_VAULT_DESTRUCTION_JOURNAL_FORMAT,
  COLLABORATIVE_VAULT_DESTRUCTION_JOURNAL_SUFFIX,
  COLLABORATIVE_VAULT_DESTRUCTION_JOURNAL_VERSION,
  MAX_COLLABORATIVE_VAULT_DESTRUCTION_JOURNAL_BYTES,
  collaborativeVaultDestructionJournalCommittedSchema,
  collaborativeVaultDestructionJournalPath,
  collaborativeVaultDestructionJournalPreparedSchema,
  collaborativeVaultDestructionJournalRecordSchema,
  createCollaborativeVaultDestructionJournal,
  readCollaborativeVaultDestructionJournal,
  reconcileCollaborativeVaultDestructionJournal,
  verifyCommittedCollaborativeVaultDestructionJournal,
  type CollaborationVaultDestructionJournalCommittedEvidence,
  type CollaborationVaultDestructionJournalCreateInput,
  type CollaborationVaultDestructionJournalReadOptions,
  type CollaborationVaultDestructionJournalScope,
  type CollaborativeVaultDestructionJournalCommittedRecord,
  type CollaborativeVaultDestructionJournalPreparedRecord,
  type CollaborativeVaultDestructionJournalRecord,
} from './collaboration-destruction-journal.js';
