import {
  credentialCopyReceiptSchema,
  credentialShowProjectionSchema,
  type CredentialCopyOptions,
  type CredentialCopyReceipt,
  type CredentialShowProjection,
} from '@kavrix/client';
import {
  apiBearerTokenSchema,
  inviteListPageResponseSchema,
  deviceIdSchema,
  inviteIdSchema,
  schemaVersionSchema,
  vaultIdSchema,
  type ControlListPageOptions,
  type GroupPayload,
  type InviteId,
  type InviteListPageResponse,
  type ItemPayload,
  type VaultId,
} from '@kavrix/schemas';
import { z } from 'zod';

import type {
  CliAddFieldRequest,
  CliAddNoteRequest,
  CliArchiveEntityRequest,
  CliArchiveFieldRequest,
  CliArchiveNoteRequest,
  CliCreateCredentialRequest,
  CliCreateGroupRequest,
  CliCredentialMutationResult,
  CliGroupMutationResult,
  CliNoteMutationResult,
  CliRemoveFieldRequest,
  CliRemoveNoteRequest,
  CliRestoreEntityRequest,
  CliRestoreFieldRequest,
  CliRestoreNoteRequest,
  CliSetFieldRequest,
  CliUpdateFieldRequest,
  CliUpdateNoteRequest,
} from './mutation-contracts.js';

export const cliStatusSchema = z
  .object({
    vaultState: z.enum(['locked', 'unlocked']),
    vaultId: vaultIdSchema.optional(),
    deviceId: deviceIdSchema.optional(),
    syncState: z.enum(['offline', 'idle', 'syncing', 'error']),
    pendingChanges: z.number().int().nonnegative(),
    lastSyncAt: z.iso.datetime({ offset: true }).optional(),
  })
  .strict()
  .superRefine((status, context) => {
    if (status.vaultState === 'unlocked' && status.vaultId === undefined) {
      context.addIssue({
        code: 'custom',
        path: ['vaultId'],
        message: 'Unlocked status requires a vault ID',
      });
    }
  });

const cliConflictIdSchema = z.string().min(16).max(256);
const cliConflictSchema = z
  .object({
    vaultId: vaultIdSchema,
    entityType: z.enum(['vault', 'group', 'item']),
    entityId: z.string().trim().min(1).max(512),
    idempotencyKey: cliConflictIdSchema,
    expectedRevision: z.number().int().nonnegative().nullable(),
    currentRevision: z.number().int().nonnegative(),
    currentState: z.enum(['present', 'deleted', 'missing']),
  })
  .strict();
const cliConflictResolutionStrategySchema = z.enum(['keep-local', 'accept-remote']);
const cliConflictResolutionRequestSchema = z
  .object({
    conflictId: cliConflictIdSchema,
    currentRevision: z.number().int().nonnegative(),
    strategy: cliConflictResolutionStrategySchema,
  })
  .strict();
const cliConflictResolutionResultSchema = z
  .object({
    status: z.enum(['accepted-remote', 'queued-local']),
    conflictId: cliConflictIdSchema,
    strategy: cliConflictResolutionStrategySchema,
    replacementIdempotencyKey: cliConflictIdSchema.nullable(),
  })
  .strict();

/**
 * The invite redemption request.
 *
 * The vault is named by the invite issuer, not chosen locally, and the device
 * ID is generated by the join coordinator so two devices can never collide on a
 * caller-supplied value. The portable key that unlocks the redeemed vault is
 * passed separately and never enters this validated object.
 */
export const cliInviteJoinRequestSchema = z
  .object({
    inviteToken: apiBearerTokenSchema,
    vaultId: vaultIdSchema,
    schemaVersion: schemaVersionSchema,
  })
  .strict();

export const cliInviteJoinResultSchema = z
  .object({
    vaultId: vaultIdSchema,
    deviceId: deviceIdSchema,
  })
  .strict();

export type CliStatus = z.infer<typeof cliStatusSchema>;
export type CliConflict = z.infer<typeof cliConflictSchema>;
export type CliConflictResolutionRequest = z.infer<
  typeof cliConflictResolutionRequestSchema
>;
export type CliConflictResolutionResult = z.infer<
  typeof cliConflictResolutionResultSchema
>;
export type CliShowResult = CredentialShowProjection;
export type CliInviteJoinRequest = z.infer<typeof cliInviteJoinRequestSchema>;
export type CliInviteJoinResult = z.infer<typeof cliInviteJoinResultSchema>;

export interface CliUseCasePorts {
  status(): Promise<CliStatus>;
  lock(): Promise<void>;
  show(groupQuery: string, credentialQuery: string): Promise<CliShowResult>;
  copy(
    groupQuery: string,
    credentialQuery: string,
    fieldQuery: string,
    options?: CredentialCopyOptions,
  ): Promise<CredentialCopyReceipt>;
  listInvitePage(
    vaultId: VaultId,
    options: ControlListPageOptions,
  ): Promise<InviteListPageResponse>;
  revokeInvite(vaultId: VaultId, inviteId: InviteId): Promise<void>;
  /**
   * Completes the two-step enrollment protocol. The adapter owns durable,
   * idempotent generation and reuse of independent enrollment/session successor
   * tokens; it must persist the resulting session token and never return it to
   * the renderer.
   */
  joinInvite(
    request: CliInviteJoinRequest,
    portableKey: string,
    serverUrl?: string,
  ): Promise<CliInviteJoinResult>;
  createGroup?(request: CliCreateGroupRequest): Promise<CliGroupMutationResult>;
  listGroups?(): Promise<readonly GroupPayload[]>;
  renameGroup?(query: string, newName: string): Promise<void>;
  archiveEntity?(request: CliArchiveEntityRequest): Promise<void>;
  restoreEntity?(request: CliRestoreEntityRequest): Promise<void>;
  deleteGroup?(query: string): Promise<void>;
  createCredential?(
    request: CliCreateCredentialRequest,
  ): Promise<CliCredentialMutationResult>;
  listCredentials?(groupQuery: string): Promise<readonly ItemPayload[]>;
  renameCredential?(groupQuery: string, query: string, newTitle: string): Promise<void>;
  deleteCredential?(groupQuery: string, query: string): Promise<void>;
  addField?(request: CliAddFieldRequest): Promise<CliCredentialMutationResult>;
  setField?(request: CliSetFieldRequest): Promise<CliCredentialMutationResult>;
  updateField?(request: CliUpdateFieldRequest): Promise<CliCredentialMutationResult>;
  archiveField?(request: CliArchiveFieldRequest): Promise<void>;
  restoreField?(request: CliRestoreFieldRequest): Promise<void>;
  removeField?(request: CliRemoveFieldRequest): Promise<void>;
  addNote?(request: CliAddNoteRequest): Promise<CliNoteMutationResult>;
  updateNote?(request: CliUpdateNoteRequest): Promise<CliNoteMutationResult>;
  archiveNote?(request: CliArchiveNoteRequest): Promise<void>;
  restoreNote?(request: CliRestoreNoteRequest): Promise<void>;
  removeNote?(request: CliRemoveNoteRequest): Promise<void>;
  reveal?(
    groupQuery: string,
    credentialQuery: string,
    fieldQuery: string,
    options?: { index?: number },
  ): Promise<{ value: string }>;
  get?(
    groupQuery: string,
    credentialQuery: string,
    fieldQuery: string,
    options?: { index?: number; reveal?: boolean },
  ): Promise<{
    groupName: string;
    credentialTitle: string;
    fieldLabel: string;
    fieldKey: string;
    fieldType: string;
    sensitive: boolean;
    value: string;
  }>;
  sync?(): Promise<CliStatus>;
  listConflicts?(): Promise<readonly CliConflict[]>;
  resolveConflict?(
    request: CliConflictResolutionRequest,
  ): Promise<CliConflictResolutionResult>;
}

export function parseStatus(value: unknown): CliStatus {
  return cliStatusSchema.parse(value);
}

export function parseConflicts(value: unknown): readonly CliConflict[] {
  return z.array(cliConflictSchema).max(100_000).parse(value);
}

export function parseConflictResolutionRequest(
  value: unknown,
): CliConflictResolutionRequest {
  return cliConflictResolutionRequestSchema.parse(value);
}

export function parseConflictResolutionResult(
  value: unknown,
): CliConflictResolutionResult {
  return cliConflictResolutionResultSchema.parse(value);
}

export function parseShowResult(value: unknown): CliShowResult {
  return credentialShowProjectionSchema.parse(value);
}

export function parseCopyReceipt(value: unknown): CredentialCopyReceipt {
  return credentialCopyReceiptSchema.parse(value);
}

export function parseInvitePage(value: unknown): InviteListPageResponse {
  return inviteListPageResponseSchema.parse(value);
}

export function parseJoinResult(value: unknown): CliInviteJoinResult {
  return cliInviteJoinResultSchema.parse(value);
}

export function parseVaultId(value: string): VaultId {
  return vaultIdSchema.parse(value);
}

export function parseInviteId(value: string): InviteId {
  return inviteIdSchema.parse(value);
}

export function shapeInviteJoinRequest(
  inviteToken: string,
  vaultId: string,
  schemaVersion: number,
): CliInviteJoinRequest {
  return cliInviteJoinRequestSchema.parse({
    inviteToken,
    vaultId: vaultIdSchema.parse(vaultId),
    schemaVersion: schemaVersionSchema.parse(schemaVersion),
  });
}
